.PHONY: clean All

All:
	@echo "----------Building project:[ Lecture1 - Debug ]----------"
	@cd "Lecture1" && "$(MAKE)" -f  "Lecture1.mk"
clean:
	@echo "----------Cleaning project:[ Lecture1 - Debug ]----------"
	@cd "Lecture1" && "$(MAKE)" -f  "Lecture1.mk" clean
