.PHONY: clean All

All:
	@echo "----------Building project:[ hemuppgifter - Debug ]----------"
	@cd "SDLProjekt_Mac_startup" && "$(MAKE)" -f  "hemuppgifter.mk"
clean:
	@echo "----------Cleaning project:[ hemuppgifter - Debug ]----------"
	@cd "SDLProjekt_Mac_startup" && "$(MAKE)" -f  "hemuppgifter.mk" clean
