.PHONY: clean All

All:
	@echo "----------Building project:[ Lecture2 - Debug ]----------"
	@cd "Lecture2" && "$(MAKE)" -f  "Lecture2.mk"
clean:
	@echo "----------Cleaning project:[ Lecture2 - Debug ]----------"
	@cd "Lecture2" && "$(MAKE)" -f  "Lecture2.mk" clean
