.PHONY: clean All

All:
	@echo "----------Building project:[ UsageFault - Debug ]----------"
	@cd "UsageFault" && "$(MAKE)" -f  "UsageFault.mk" && "$(MAKE)" -f  "UsageFault.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ UsageFault - Debug ]----------"
	@cd "UsageFault" && "$(MAKE)" -f  "UsageFault.mk" clean
