.PHONY: clean All

All:
	@echo "----------Building project:[ Delay - Debug ]----------"
	@cd "basic_io" && "$(MAKE)" -f  "Delay.mk" && "$(MAKE)" -f  "Delay.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Delay - Debug ]----------"
	@cd "basic_io" && "$(MAKE)" -f  "Delay.mk" clean
