.PHONY: clean All

All:
	@echo "----------Building project:[ 6_4 - Debug ]----------"
	@cd "6_4" && "$(MAKE)" -f  "6_4.mk" && "$(MAKE)" -f  "6_4.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ 6_4 - Debug ]----------"
	@cd "6_4" && "$(MAKE)" -f  "6_4.mk" clean
